language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - extra-android-m2repository
    - extra-android-support
    - android-24
    - sys-img-armeabi-v7a-android-24

jdk:
  - oraclejdk8

script:
  - chmod +x gradlew
  - ./gradlew clean build connectedCheck


notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
